apiVersion: v1
kind: Service
metadata:
  name: go-api-svc
  labels:
    app: go-api
spec:
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081      #target port has to be the container port that you expose
  selector:                 #most important thing in the service is selector..This selector has to match with the label you provided in pod specification in deployment file. 
      app: my-new-api
  type: NodePort